name: sf_pay
description: "SF-Pay Mobile Wallet"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0

flutter:
  uses-material-design: true
